//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excho.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentication
    {
        public string Id { get; set; }
        public int Account { get; set; }
        public string Factor { get; set; }
    }
}
